### ISSUE TITLE
add tmp and log folders to `gitignore`

### ISSUE THREAD

**Issue by stevejpurves** [Notebooks-Now/submission-myst-full#6]
When building with myst locally, folders containing build logs can be created at the project root e.g. `article_tex_logs` and `article_pdf+tex_logs` and potentially/probably for logs on other export targets.

We should add these to the `.gitignore` file

**Comment by stevejpurves** [comment]
@fwkoch do you know which folders could be created outside of the `_build` folder? (or where to look to learn that?) i'm not sure if I groked the folder names correctly here.

**Comment by rowanc1** [comment]
This happens when the output is specified directly! If you don't specify the output, it stays in the `_build` folder.

**Comment by fwkoch** [comment]
Yeah, for `format: pdf+tex` where output pdf file is specified, the `*_pdf_logs` and `*_pdf_tex` folders are created adjacent to the pdf file. This is the only case where logs show up outside the `_build/temp` folder, I'm pretty sure.

Shouldn't be a problem to add `*_pdf_logs` and `*_pdf_tex` to the gitignore though.

**Comment by stevejpurves** [comment]
added here: https://github.com/Notebooks-Now/submission-myst-full/commit/4faeafb199f035858ed21f21e53e642f9862bd7d
